# Generated by Django 3.2 on 2021-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_orders', '0005_auto_20210409_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
