# Generated by Django 3.2 on 2021-04-09 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('price', models.IntegerField(max_length=10)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
