version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic


volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge