version: "3.9"


services:
  elasticsearch:
    image: elasticsearch:7.17.5
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      bootstrap.memory_lock: "true"
      ELASTICSEARCH_PASSWORD: "password"
      ELASTICSEARCH_USERNAME: "username"
      XPACK_SECURITY_ENABLED: "true"

    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic


volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
